server:
  port: 9000

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kubydata
    username: root
    password: routrout
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none  # Empêche Hibernate de modifier le schéma
    show-sql: true  # Affiche les requêtes SQL dans les logs
  h2:
    console:
      enabled: true
      path: /h2-console  # Confirme le chemin d'accès à la console H2
  sql:
    init:
      mode: always  # Assure l'exécution des scripts au démarrage
